name: Windows Test

on:
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup with Maven
        run: mvn clean
      - name: Build with Maven
        run: mvn -e test
      - run: echo "🍏 This job's status is ${{ job.status }}."